spring:
  cloud:
    openfeign:
      client:
        config:
          weather: # ??? ???????? ?????? feignCleint ?? WeatherExternalApi
            url: http://localhost:8090/api/weather # ?? ????? ?????? ????? ?????????? ?????? ?? WeatherExternalApi
            connection-timeout: 5000 # ??????? ??????????? feign client ????? ????? ???????????? ??????????, ????? ??????
            read-timeout: 5000 # ??????? ??????????? feign client ????? ????? ????? ????? ?????????? ??? ???????????, ????? ?????? SocketTimeoutException
